### ISSUE TITLE
Get a list wont work

### ISSUE THREAD

**Issue by Betacarotin** [humhub/humhub-modules-mostactiveusers#6]
It works fine with admin account, with user accounts its not possible to get the list. Its only loading but nothing happens
/BC

**Comment by UtmostCreator** [comment]
Good day, @Betacarotin.

I checked it on my dashboard, and it is working w/o any issues.
Here is the screenshot. As for logged-in user (**on the left side**) and as for guest (not logged in user - **on the right side**) 

![image](https://user-images.githubusercontent.com/22347676/85727033-59ef6b80-b6ff-11ea-9228-822d31fb6de6.png)

Let me know if I missed something, or there is something else should be displayed.

Thank you for your attention!
