### ISSUE TITLE
Most active user sorted by id

### ISSUE THREAD

**Issue by edsy** [humhub/humhub-modules-mostactiveusers#8]
This appears for widget and list. Counts are correct but the user are sorted by their id.

**Comment by ValeSauer** [comment]
yup. Same thing here.

**Comment by radu-stanescu** [comment]
same also

**Comment by UtmostCreator** [comment]
Good day!

By what kind of criteria should be used for sorting?

Thank you!

**Comment by luke-** [comment]
I think the sorting should somehow be based on the activity. Active users first.

**Comment by UtmostCreator** [comment]
I believe it should be closed as it checks the number of likes, comments, and posts.
here is the file with it:
https://github.com/humhub-contrib/mostactiveusers/blob/master/models/ActiveUser.php#L32-L36

**Comment by luke-** [comment]
Ok, thanks for your investigation!
